sudo: false
language: node_js
node_js:
  - "0.12" # Ensure that we don't accidently slip in ES6 features
  - "0.10" # Ensure that we work on older environments
  - "0.8"  # like, really old
  - "6"
  - "8"
  - "9"
matrix:
  allow_failures:
     - node_js: "0.8"
     - node_js: "0.10"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls && cat coverage/lcov.info | coveralls"
notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
